#服务器端口
server:
  port: 81

#数据库连接参数
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jd?useSSL=false&serverTimeZone=Asia/Shanghai
    username: root
    password: root
  #es连接参数
  elasticsearch:
    rest:
      uris: 192.168.175.125:9200

#mybatis配置（使用注解时不需要该配置）
mybatis:
  type-aliases-package: com.shiju.domain #别名
  #  config-location:   #核心配置文件位置
  #  mapper-locations:   #映射配置文件位置


#dubbo配置
dubbo:
  application:
    name: jd-search-service
  registry:
    address: zookeeper://192.168.175.125:2181
  scan:
    base-packages: com.shiju.service
  protocol:
    port: 20880
    name: dubbo
